baseURL = "https://techbag.app/"
languageCode = "en"
theme = "lynx"

title = "TechBag.app | An awesome bag👌"
copyright = "Copy, _right?_ :thinking_face:"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "TechBag.app"
  headline = "An awesome bag:ok_hand:"
  image = "img/bagpack.png"  # path relative to static directory
  

  links = [
    { send = { href = "https://send.techbag.app", text = "Send large files", target = "_blank" } },
    { paste = { href = "https://paste.techbag.app", text = "Secure paste share", target = "_blank" } },
    { draw = { href = "https://excalidraw.techbag.app", text = "Draw, Virtual whiteboard", target = "_blank" } },
    { rallly = { href = "https://rallly.techbag.app", text = "Rallly, Schedule Group Meetings", target = "_blank" } },              
    { github = "https://github.com/komogoto/techbag.app" },
    { about = { href = "./about/", text = "About TechBag.app", target = "_self" } },               
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
