baseURL = "https://techbag.app/"
languageCode = "en"
theme = "lynx"

title = "TechBag.app | An awesome bag👌"
copyright = "Copy, _right?_ :thinking_face:"

#[params]
#	favicon = "img/bagpack.png"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "TechBag.app"
  headline = "An awesome bag:ok_hand:"
  image = "img/bagpack.png"  # path relative to static directory
  

  links = [  
    { github = "https://github.com/theoricher/techbag.app" },
    { about = { href = "./about/", text = "About TechBag.app" } },               
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
